<a href="https://colab.research.google.com/github/Welle-Kim/Mathematics-for-SW-AI-/blob/master/SW%26AI_%EC%A0%84%EA%B3%B5_%EC%A7%84%EC%9E%85%EC%9D%84_%EC%9C%84%ED%95%9C_%EC%88%98%ED%95%991.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#벡터의 차원
import numpy as np
x=np.array([1,2,3])
print(x)
print(x[0])
print(x[1])
print(x[2])
print(len(x))
print(x.shape)
print(x.ndim)

[1 2 3]
1
2
3
3
(3,)
1


In [3]:
#행렬의 차원
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(A[0,0])
print(A[0,1])
print(A[2,1])
print(A.shape)
print(A.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
8
(3, 3)
2


In [6]:
#3차원 텐서
import numpy as np
T = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(T)
print(T[0,0,0])
print(T[0,0,1])
print(T[1,2,1])
print(T.shape) # 3*3행렬이 두겹
print(T.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
1
2
17
(2, 3, 3)
3


In [32]:
import numpy as np
A=np.random.randint(2,size=(2,3))
B=np.random.randint(2,size=(2,3))
print("A=",A)
print("B=",B)
np.array_equal(A,B)

A= [[0 1 0]
 [1 1 0]]
B= [[1 1 1]
 [0 0 1]]


False

In [36]:
import numpy as np
A=np.array([[2,-1,1],[-1,3,4]])
B=np.array([[-1,2,-3],[2,0,-1]])
x=np.array([3,1,-2,4])
y=np.array([-1,-3,5,1])
print(A+B,"\n")
print(x-y,"\n")
print(A+(2*B-3*A))

[[ 1  1 -2]
 [ 1  3  3]] 

[ 4  4 -7  3] 

[[ -6   6  -8]
 [  6  -6 -10]]
